#!/bin/bash

if [ "$1" == "-?" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "" ]
then
	echo -e "Usage: bk2github --backup\n\nBash script used to backup files/directories to github.\nEdit the script to change the files that should be backed up to github.\nMake sure to also adjust the github repository which will be cloned & pushed.\n"
elif [ "$1" == "--backup" ]
then
	# files & direcotries to backup to github, modify to add new ones
	backup_files=()
	backup_files[0]="$HOME/.config/i3/"
	backup_files[1]="$HOME/.config/i3lock-next/"
	backup_files[2]="$HOME/.config/polybar/"
	backup_files[3]="$HOME/.config/dunst/"
	backup_files[4]="$HOME/.config/sxiv/"
	backup_files[5]="$HOME/.config/ranger/"
	backup_files[6]="$HOME/.config/rofi/"
	backup_files[7]="$HOME/.vim/"
	backup_files[8]="$HOME/.vimrc"
	backup_files[9]="$HOME/.bashrc"
	backup_files[10]="$HOME/.xinitrc"
	backup_files[11]="$HOME/.config/compton/"
	backup_files[12]="/etc/bash.bashrc"

	# create temporary directory
	temp_dir="/tmp/bk2github_temp"
	if [ -d $temp_dir ]
	then
		rm -rf $temp_dir && mkdir $temp_dir
	fi

	# clone git repository: dotfiles
	git clone https://github.com/recktard/dotfiles $temp_dir
	# backup the README.md file, not to remove!
	mv -v $temp_dir/README.md $temp_dir/.README.md
	# now remove all files/dirs and move .README.md to README.md
	rm -rf $temp_dir/* && mv -v $temp_dir/.README.md $temp_dir/README.md

	file_count="${#backup_files[@]}"
	file_multipl=0
	counter=0

	# copy files/directories to backup into temporary dir
	while [ $counter -lt $file_count ]
	do
		cp -rv ${backup_files[$file_multipl]} $temp_dir

		file_multipl=$(( $file_multipl+1 ))
		counter=$(( $counter+1 ))
	done

	mkdir $temp_dir/rcfiles/

	# .vim and .vimrc get into vim/ directory
	mv -v $temp_dir/.vim $temp_dir/vim/ && mv .v $temp_dir/.vimrc $temp_dir/vim/
	# then move any other rcfile into rcfiles/
	mv -v $temp_dir/*rc $temp_dir/rcfiles/ && mv -v $temp_dir/.*rc $temp_dir/rcfiles/ 

	# add all the files to git
	cd $temp_dir && git add . && git commit -m "new things :o" && git push

	# clean everything
	rm -rf $temp_dir
else
	echo -e "bk2github: wrong command\nTry 'bk2github --help' for more information."	
fi
