#!/bin/bash

# netcat sender script

read -e -p "Enter file/directory to send: " fname

# check if file/directory exists
if [ -f $fname ] || [ -d $fname ]; then
	# get ip addr
	read -e -p "Enter receiving IP: " receiving_ip
	# check if receiving client can be pinged
	if ping -c 1 $receiving_ip >/dev/null; then
		# get port
		read -e -p "Enter Port: " port
		# ask for confirmation
		read -e -p "Confirm sending '$fname' to '$receiving_ip:$port' (Y/N): " confirm
		if [[ $confirm == y ]] || [[ $confirm == Y ]] || [[ $confirm == yes ]] || [[ $confirm == Yes ]]; then
			# netcat and tar to send file/folder
			cat $fname | netcat $receiving_ip $port
		else
			echo "Error: File transfer not working"
		fi
	else
		echo "Error: Cannot reach receiving client! Check connectivity. Aborting."
	fi
elif [ $fname == "" ]; then
	echo "No file/directory selected!"
	~/ownCloud/Linux/scripts/netcat-send && exit
else
	echo "$fname does not exist!"
	~/ownCloud/Linux/scripts/netcat-send && exit
fi
