#!/bin/sh

# Record terminal with asciinema and save clips under ~/tmp/clips

clip_name=`date +"%b%d::%H%M%S"`

if [ -d ~/clips ]; then
	asciinema rec ~/tmp/clips/$clip_name.clip
else 
	read -e -p "Create directory: $HOME/tmp/clips? (Y/n) " clip_dir
	if [[ $clip_dir == "" ]] || [[ $clip_dir == "y" ]] || [[ $clip_dir == "Y" ]] || [[ $clip_dir == "yes" ]] || [[ $clip_dir == "YES" ]]; then
		mkdir -p $HOME/tmp/clips
		asciinema rec ~/tmp/clips/$clip_name.clip
	else 
		exit
	fi
fi
