#!/bin/bash

# Script to run thunderbird

thunderbird_status=`pgrep -f thunderbird | wc -l`

if [[ $thunderbird_status = 0 ]]
then
	thunderbird &
elif [[ $thunderbird_status > 0 ]]
then
	pgrep -f thunderbird | xargs kill
	thunderbird &
fi
