#!/bin/sh

# Help
if [[ $1 == "" ]] || [[ $1 == "help" ]]
then
	printf "Usage: xdisplay [RESET] DISPLAY SIDE\n
	RESET	= xdisplay reset
	DISPLAY	= hdmi, dvi
	SIDE	= left, right, mirror\n\n"
	printf "Shell script for xrandr to quickly add second monitor.\n"
elif [[ $1 == "reset" ]] || [[ $1 == "RESET" ]]
then
	xrandr --output DP1 --off
	xrandr --output HDMI1 --off
	sleep 5; ~/.config/polybar/launch.sh &
else 
	# Get display
	if [[ $1 == "dvi" ]] || [[ $1 == "DVI" ]]
	then
		xscreen_display="DP1"	
	elif [[ $1 == "hdmi" ]] || [[ $1 == "HDMI" ]]
	then
		xscreen_display="HDMI1"
	else 
		echo "Error: Display not found"
	fi

	# Get display side
	if [[ $2 == "left" ]] || [[ $2 == "LEFT" ]] 
	then
		xscreen_side="--left-of"
	elif [[ $2 == "right" ]] || [[ $2 == "RIGHT" ]]
	then
		xscreen_side="--right-of"
	elif [[ $2 == "mirror" ]] || [[ $2 == mirror ]]
	then
		xrandr --output eDP1 --auto --output $xscreen_display --auto --same-as eDP1 &
		sleep 5; ~/.config/polybar/launch.sh &
	else
		echo "Error: Side not found"
	fi

	xrandr --auto --output eDP1 --mode 1920x1080 $xscreen_side $xscreen_display &
	sleep 5; ~/.config/polybar/launch.sh &
fi
